version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: binitright_db

  java-app:
    image: ${JAVA_IMAGE}
    ports:
      - "${JAVA_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/binitright_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DB_ACTION}
    depends_on:
      - db