version: '3.8'
services:
  db:
    # No ports section here! Keep it private.
    restart: always
    environment:
      MYSQL_DATABASE: binitright
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_prod_data:/var/lib/mysql

  java-app:
    image: ${JAVA_IMAGE}
    restart: always
    # This ensures that if the DB restarts, the app waits for it to be 'healthy'
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_prod_data: