# Only update schema, never drop it
#spring.jpa.hibernate.ddl-auto=update
# Disable automatic SQL initialization
#spring.sql.init.mode=never

# Recreate the schema on every startup
spring.jpa.hibernate.ddl-auto=create
# Forces Spring to run data.sql even on non-embedded databases
spring.sql.init.mode=always

# Ensures Hibernate finishes building tables BEFORE data.sql runs
spring.jpa.defer-datasource-initialization=true